apiVersion: v2
name: dragonfly
version: 0.1.0
appVersion: "0.1.0"
description: Dragonfly is an intelligent P2P based image and file distribution system
type: application
keywords:
- dragonfly
- d7y
- P2P
- image
home: https://d7y.io/
sources:
- https://github.com/dragonflyoss/Dragonfly2
