apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dragonfly.scheduler.fullname" . }}
  namespace: {{ .Values.installation.namespace }}
  labels:
    app: {{ template "dragonfly.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  scheduler.yaml: |-
    deubug: {{ .Values.scheduler.config.debug }}
    server:
      port: {{ .Values.scheduler.containerPort }}
    worker:
{{ toYaml .Values.scheduler.config.worker | indent 6 }}
    cdn:
      list:
        - - cdn-name: {{template "dragonfly.cdn.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            ip: {{template "dragonfly.cdn.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            rpc-port: {{ .Values.cdn.service.port }}
            download-port: {{ .Values.cdn.service.nginxPort }}
